name: Android Release

on:

  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Decode keystore
        run: |
          echo "${{ vars.KEYSTORE_BASE64 }}" | base64 --decode > ${{ github.workspace }}/accountassistant.jks

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build Release APK
        env:
          STORE_PASSWORD: ${{ vars.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ vars.KEY_PASSWORD }}
          KEY_ALIAS: ${{ vars.KEY_ALIAS }}
          JKS_PATH: ${{ github.workspace }}/accountassistant.jks
        run: ./gradlew assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/*.apk
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
